### PR TITLE
Redirect only when auth is required

### LINKED ISSUE #154: Improve redirectTo behavior
The `redirectTo` feature is great, but it is way too eager to activate and does not respect the `auth.mode` of routes.

From the docs:

> Note that using `redirectTo` with authentication mode `'try'` will cause the protected endpoint to always redirect, voiding `'try'` mode.

And also:

> `redirectOnTry` - if `false` and route authentication mode is `'try'`, authentication errors will not trigger a redirection. Requires hapi version 6.2.0 or newer. Defaults to `true`

This is all needlessly silly and complicated. I bet at least 95% of the time what people want is for `redirectTo` to only affect requests whose auth mode is `required`.

Currently I have to add this to every single route where auth is `optional`.

```js
plugins : {
    'hapi-auth-cookie' : {
        redirectTo : false
    }
}
```

I'm failing to think of a scenario where I _would_ want `redirectTo` and `optional` / `try` together. But if there is one, it is definitely not the common case.

I propose that `redirectTo` only triggers for `required` auth. We could have a `redirectOnTry: true` to re-enable the old behavior, but it's still a breaking change. And with the new behavior, I'm not sure anyone actually even needs the `redirectOnTry` option at all.

### PR DESCRIPTION
**Pull request by sholladay**
*Update: for hapi 17 support, see PR #186*

Fixes #154.

**Q: What's the purpose of `redirectTo`?**
**A: Redirecting preempts the original route handler to protect it from unauthenticated requests.**

**Q: But what about routes that explicitly want to process unauthenticated requests? Isn't this the purpose of `optional` and `try` modes?**
**A: `redirectTo` screws them up. Oops.**

Okay, so ... let's fix this and respect the auth mode.

___

This changes two closely related things. First and most importantly, it changes the behavior of `redirectTo` so that its effects only apply to auth mode `required`. Thus it no longer conflicts with the intent of `optional` and `try` modes. Secondly, it removes `redirectOnTry`.

I removed `redirectOnTry` because:

 - It seems to only be a workaround for a problem that this PR solves.
 - I don't believe anyone actually wants to redirect on `try`. I think everyone who is using `try` just set this to `false`, which is redundant now given the new behavior of `redirectTo`.
 - The changing default behavior of `redirectTo` makes this semver major anyway. Now is a good time to remove it so that migration is easier and more intuitive.

The diff for the tests is poor. Basically just added a test for `optional` auth mode, fixed the one for `try`, and removed the obsolete `redirectOnTry` test. Also fixed `uri` -> `url` ([see this](https://github.com/nodejs/node/issues/1435#issuecomment-142650372)) and the [weird executables](https://github.com/hapijs/discuss/issues/438) while I was here. Happy to split things up if necessary.

### CODE REVIEW

**Comment by jaw187** [comment]
@sholladay Thanks for the PR.

This feature was inherited with the project, so I'm not entirely sure what the motivation is for redirecting with optional auth.  Since the feature exists, I'm not overly interested in making such a big change if we're overlooking some common case.

Considering there is a flag that can be set to address your changes, I think it's best to leave everything as is.  But I'm willing to think about it more.

**Comment by sholladay** [comment]
> there is a flag that can be set to address your changes

Nope. There is no flag that fixes the `redirectTo` shenanigans for `optional` mode. Sure, you could introduce another hack and implement a `redirectOnOptional` or we can just fix `redirectTo`.

**Comment by sholladay** [comment]
Hi @mrlannigan thanks for stepping up to maintain this module. Would you mind giving your thoughts on this and letting me know if there is any chance of getting this in? If so, I will fix the merge conflicts.

I have been using a fork of this project because it's been too much of a burden to add boilerplate to every route and then explain to people on my team why the behavior is inconsistent for different auth modes.

**Comment by mrlannigan** [comment]
@sholladay Thanks for the contribution and #186. Over the next week, I will continue the conversation in the new PR.

Closing this one.

**Pull request closed without merging**
