### PR TITLE
Upgrade to hapi 18

### LINKED ISSUE #204: Update for hapi 18
It needs to handle URL objects:
https://github.com/hapijs/hapi-auth-cookie/blob/cb8796f9c7f22fd8af10adf3563a5f702ad57e25/lib/index.js#L233

### PR DESCRIPTION
**Pull request by rluba**
This closes #204 

See https://github.com/hapijs/hapi/issues/3871 for details on hapi 18

### CODE REVIEW

**Comment by rluba** [comment]
The failing builds seem to be related to node 11 in general and not caused by this PR.

**Comment by janl** [comment]
Heya, not to pile on or anything, just wondering if there is something we can do to help get this merged ✌️💖

**Comment by kanongil** [comment]
It would be nice to get this sorted, to make the v18 update safer for our users.

@hueniverse Can you find some time to update this module?

**Comment by wavemotionio** [comment]
+1. Hapi is amazing.  It is great to see more and more adopters of server-side JS.  This plugin, and the entire plugin system, makes working with this library a dream come true.

ISSUE: When a user attempts to navigate to a protected route, while unauthenticated, the `appendNext: true` setting is causing `?next=undefined` every time.  In our applications' case, this leads to looping redirects and finally lands the user on the entry/home page rather than the sub-page the user originally intended to visit.

**Comment by janl** [comment]
<3

**Pull request merged**
