### PR TITLE
Added mutable encoding

### PR DESCRIPTION
**Pull request by janrueckert**

### CODE REVIEW

**Comment by jaw187** [comment]
Missing test for code coverage.  Look to https://github.com/hapijs/statehood/blob/master/test/index.js for examples of tests which modify the cookie encoding

**Comment by jaw187** [comment]
@janrueckert what encoding options are you considering to use?

**Comment by janrueckert** [comment]
@jaw187 none, base64, base64json

**Comment by jaw187** [comment]
If you use those encodings, the session cookie can be modified by the client.  Is that the desired result?

**Comment by hueniverse** [comment]
This makes no sense. You need the cookie encrypted or the entire security property goes away.

**Comment by janrueckert** [comment]
If the content of the cookie or session is encrypted previously or just a random String for internal purposes its totally suggestive.

**Comment by hueniverse** [comment]
@janrueckert you might as well implement your own scheme then. Adding options to turn off the key security feature is a bad idea.

**Comment by jaw187** [comment]
@janrueckert I'm going to close this.  For future reference, please make sure to ensure a PR has 100% code coverage.

**Pull request closed without merging**
